apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: mongo-pacman
  name: mongodb
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mongodb
    spec:
      containers:
      - image: quay.io/jduimovich0/mongo-backend@sha256:14a0d764c8b1945cc6cabe4da6194dcfe51503ad63342e083f6d3b7e1097acf8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
